// ─────────────────────────────────────────────────────────────────────
// IMOVAI OS v10 — Dados Iniciais Centralizados
// ─────────────────────────────────────────────────────────────────────

import type { Lead, Property, Stage, Message } from './types';

export const LEADS_INIT: Lead[] = [
  { id:1, name:'Carlos Mendonça',  phone:'(47) 99201-3344', email:'carlos.m@email.com',
    budget:'R$ 320.000',  budgetNum:320000, income:'R$ 8.500/mês',  incomeNum:8500,
    entry:'R$ 50.000',   entryNum:50000,  location:'Balneário Piçarras', propertyType:'Apartamento',
    intent:'moradia', status:'qualificado', temp:'hot', score:92, lifeEvent:'Mudança de emprego detectada',
    lastMsg:'2h atrás', lastMsgTs:Date.now()-7200000, avatar:'CM', code:'2041', assignedTo:'Jorge',
    aiNotes:"Alta intenção. Mencionou 'minha esposa adorou'. Sensível a prazo.",
    tags:['lead-qualificado','interesse-visita','life-event'], paused:false, source:'instagram',
    closingProbability:0.78, revenueExpected:9600, visitScheduled:true, partnerMentioned:true, fundingSimulated:false, satisfaction:4.8,
    memory:{ propertiesViewed:['2041','2088'], offersMade:[], objections:['preço','localização'], favoriteRegions:['Balneário Piçarras'] },
    timeline:[
      {event:'Primeiro contato via Instagram',time:'09:12',icon:'📲',type:'contact'},
      {event:'IA detectou mudança de emprego',time:'09:13',icon:'🔍',type:'insight'},
      {event:'Qualificado pela IA',time:'09:14',icon:'🧠',type:'ai'},
      {event:'Visita agendada Apto 2041',time:'09:16',icon:'📅',type:'action'},
      {event:'Abriu fotos do imóvel 3x',time:'09:18',icon:'👁',type:'behavior'},
    ],
    behavioralData:{emailOpenRate:0.85,linkClicks:7,siteVisits:4,averageTimeOnSite:342,preferredChannels:['whatsapp','email'],objectionHistory:['preço','localização']},
    sentimentTrend:[72,75,80,82,88,91], dealVelocity:4.2, qualityScore:89,
    documents:[{name:'Simulação Financeira',status:'enviado',date:'há 2 dias'},{name:'Proposta Formal',status:'pendente',date:null}],
  },
  { id:2, name:'Fernanda Lima', phone:'(47) 98877-2211', email:'fernanda.lima@gmail.com',
    budget:'R$ 180.000', budgetNum:180000, income:'R$ 5.200/mês', incomeNum:5200,
    entry:'R$ 30.000', entryNum:30000, location:'Penha', propertyType:'Studio',
    intent:'investimento', status:'visitou', temp:'warm', score:74, lifeEvent:null,
    lastMsg:'1d atrás', lastMsgTs:Date.now()-86400000, avatar:'FL', code:null, assignedTo:'Jorge',
    aiNotes:'Investidora racional. Foco em rentabilidade e yield. Alta abertura de email.',
    tags:['lead-qualificado','investidor','airbnb'], paused:false, source:'google',
    closingProbability:0.52, revenueExpected:5400, visitScheduled:false, partnerMentioned:false, fundingSimulated:true, satisfaction:4.2,
    memory:{ propertiesViewed:['1055','3122'], offersMade:[], objections:[], favoriteRegions:['Penha','Barra Velha'] },
    timeline:[
      {event:'Captado via Google Ads',time:'14:30',icon:'🎯',type:'capture'},
      {event:'IA calculou ROI potencial 12.1%',time:'14:35',icon:'📊',type:'ai'},
      {event:'Visitou Studio 1055',time:'10:00',icon:'🏠',type:'visit'},
    ],
    behavioralData:{emailOpenRate:0.92,linkClicks:12,siteVisits:8,averageTimeOnSite:523,preferredChannels:['email','whatsapp'],objectionHistory:[]},
    sentimentTrend:[60,63,68,70,72,74], dealVelocity:2.1, qualityScore:71,
    documents:[{name:'Análise de Rentabilidade',status:'enviado',date:'há 3 dias'}],
  },
  { id:3, name:'Ricardo Souza', phone:'(47) 99654-8822', email:'ricardosouza@empresa.com',
    budget:'R$ 500.000', budgetNum:500000, income:'R$ 15.000/mês', incomeNum:15000,
    entry:'R$ 80.000', entryNum:80000, location:'Navegantes', propertyType:'Cobertura',
    intent:'moradia', status:'proposta', temp:'hot', score:88, lifeEvent:'Patrimônio aumentado 40%',
    lastMsg:'3h atrás', lastMsgTs:Date.now()-10800000, avatar:'RS', code:'4055', assignedTo:'Jorge',
    aiNotes:'High ticket. Próximo ao fechamento. Responde bem a exclusividade.',
    tags:['lead-qualificado','alto-padrao','life-event','urgente'], paused:true, source:'indicacao',
    closingProbability:0.85, revenueExpected:15000, visitScheduled:true, partnerMentioned:false, fundingSimulated:true, satisfaction:4.9,
    memory:{ propertiesViewed:['4055'], offersMade:['4055'], objections:['financiamento'], favoriteRegions:['Navegantes'] },
    timeline:[
      {event:'Indicado por cliente Marcos',time:'11:20',icon:'🤝',type:'referral'},
      {event:'IA detectou aumento de patrimônio',time:'11:25',icon:'💰',type:'insight'},
      {event:'Visita Cobertura 4055',time:'14:00',icon:'🏠',type:'visit'},
      {event:'Proposta enviada',time:'17:30',icon:'📄',type:'proposal'},
      {event:'Abriu proposta 4x',time:'17:45',icon:'👁',type:'behavior'},
    ],
    behavioralData:{emailOpenRate:1.0,linkClicks:15,siteVisits:12,averageTimeOnSite:678,preferredChannels:['whatsapp','phone'],objectionHistory:['financiamento']},
    sentimentTrend:[75,80,84,86,89,91], dealVelocity:6.8, qualityScore:94,
    documents:[{name:'Proposta Cobertura 4055',status:'aberto_4x',date:'há 1 dia'},{name:'Contrato Preliminar',status:'pendente',date:null}],
  },
  { id:4, name:'Ana Paula Vieira', phone:'(47) 99123-7766', email:'anapaula@email.com',
    budget:'R$ 250.000', budgetNum:250000, income:'R$ 6.000/mês', incomeNum:6000,
    entry:'R$ 40.000', entryNum:40000, location:'Balneário Piçarras', propertyType:'Apartamento',
    intent:'moradia', status:'novo', temp:'cold', score:41, lifeEvent:null,
    lastMsg:'5d atrás', lastMsgTs:Date.now()-432000000, avatar:'AV', code:null, assignedTo:'Jorge',
    aiNotes:'Lead frio. Reativação automática programada. Primeira habitação.',
    tags:['reativacao-pendente','baixo-engajamento'], paused:false, source:'trafego_pago',
    closingProbability:0.21, revenueExpected:7500, visitScheduled:false, partnerMentioned:false, fundingSimulated:false, satisfaction:null,
    memory:{ propertiesViewed:[], offersMade:[], objections:[], favoriteRegions:['Balneário Piçarras'] },
    timeline:[
      {event:'Lead captado via Meta Ads',time:'09:00',icon:'📲',type:'capture'},
      {event:'Conversa sem qualificação',time:'09:05',icon:'💬',type:'contact'},
      {event:'IA agendou reativação 3d/7d/30d',time:'09:10',icon:'⏰',type:'ai'},
    ],
    behavioralData:{emailOpenRate:0.12,linkClicks:0,siteVisits:1,averageTimeOnSite:45,preferredChannels:['whatsapp'],objectionHistory:[]},
    sentimentTrend:[40,38,42,39,41,41], dealVelocity:0.3, qualityScore:38,
    documents:[],
  },
  { id:5, name:'Marcos Oliveira', phone:'(47) 98555-4433', email:'marcos@oliveira.com',
    budget:'R$ 420.000', budgetNum:420000, income:'R$ 12.000/mês', incomeNum:12000,
    entry:'R$ 70.000', entryNum:70000, location:'Penha', propertyType:'Casa',
    intent:'investimento', status:'agendado', temp:'warm', score:67, lifeEvent:null,
    lastMsg:'6h atrás', lastMsgTs:Date.now()-21600000, avatar:'MO', code:'3098', assignedTo:'Jorge',
    aiNotes:'Multi-compra potencial. Investidor serial. Pode fechar 2+ unidades.',
    tags:['investidor','multi-unidade','potencial-alto'], paused:false, source:'organico',
    closingProbability:0.52, revenueExpected:25200, visitScheduled:true, partnerMentioned:false, fundingSimulated:false, satisfaction:4.5,
    memory:{ propertiesViewed:['3098','6077'], offersMade:[], objections:['prazo'], favoriteRegions:['Penha'] },
    timeline:[
      {event:'Primeiro contato orgânico',time:'10:00',icon:'🌱',type:'contact'},
      {event:'IA detectou potencial multi-compra',time:'10:05',icon:'💡',type:'insight'},
      {event:'Visita agendada Casa 3098',time:'11:30',icon:'📅',type:'action'},
    ],
    behavioralData:{emailOpenRate:0.78,linkClicks:9,siteVisits:6,averageTimeOnSite:412,preferredChannels:['whatsapp','email'],objectionHistory:['prazo']},
    sentimentTrend:[55,60,63,65,67,67], dealVelocity:3.1, qualityScore:65,
    documents:[{name:'Portfólio Investidor',status:'enviado',date:'há 5 dias'}],
  },
  { id:6, name:'Juliana Costa', phone:'(47) 99876-1100', email:'juliana.costa@gmail.com',
    budget:'R$ 290.000', budgetNum:290000, income:'R$ 9.000/mês', incomeNum:9000,
    entry:'R$ 45.000', entryNum:45000, location:'Barra Velha', propertyType:'Apartamento',
    intent:'moradia', status:'qualificado', temp:'hot', score:85, lifeEvent:'Divórcio recente (detectado)',
    lastMsg:'1h atrás', lastMsgTs:Date.now()-3600000, avatar:'JC', code:'2041', assignedTo:'Jorge',
    aiNotes:'Emotiva. Linguagem emocional converte mais. Janela temporal estreita.',
    tags:['lead-qualificado','urgencia-media','life-event'], paused:false, source:'instagram',
    closingProbability:0.70, revenueExpected:8700, visitScheduled:false, partnerMentioned:false, fundingSimulated:false, satisfaction:4.6,
    memory:{ propertiesViewed:['2041'], offersMade:[], objections:[], favoriteRegions:['Barra Velha'] },
    timeline:[
      {event:'Lead orgânico Instagram',time:'08:45',icon:'📲',type:'capture'},
      {event:'IA detectou life event: divórcio',time:'08:50',icon:'🔍',type:'insight'},
      {event:'Qualificada com alta pontuação',time:'09:00',icon:'🧠',type:'ai'},
    ],
    behavioralData:{emailOpenRate:0.95,linkClicks:6,siteVisits:3,averageTimeOnSite:287,preferredChannels:['instagram','whatsapp'],objectionHistory:[]},
    sentimentTrend:[65,70,75,78,82,85], dealVelocity:5.2, qualityScore:83,
    documents:[],
  },
  { id:7, name:'Diego Ferreira', phone:'(47) 98800-1234', email:'diego.f@invest.com',
    budget:'R$ 750.000', budgetNum:750000, income:'R$ 22.000/mês', incomeNum:22000,
    entry:'R$ 150.000', entryNum:150000, location:'Balneário Camboriú', propertyType:'Cobertura',
    intent:'investimento', status:'novo', temp:'warm', score:71, lifeEvent:'Venda de empresa detectada',
    lastMsg:'12h atrás', lastMsgTs:Date.now()-43200000, avatar:'DF', code:null, assignedTo:'Jorge',
    aiNotes:'High ticket investor. Recém vendeu empresa. Perfil BC e Itapoá.',
    tags:['alto-padrao','investidor','life-event','bc'], paused:false, source:'indicacao',
    closingProbability:0.45, revenueExpected:22500, visitScheduled:false, partnerMentioned:false, fundingSimulated:false, satisfaction:null,
    memory:{ propertiesViewed:[], offersMade:[], objections:[], favoriteRegions:['Balneário Camboriú','Itapoá'] },
    timeline:[
      {event:'Indicado por Ricardo Souza',time:'08:00',icon:'🤝',type:'referral'},
      {event:'IA detectou venda de empresa',time:'08:05',icon:'💡',type:'insight'},
    ],
    behavioralData:{emailOpenRate:0.60,linkClicks:3,siteVisits:2,averageTimeOnSite:180,preferredChannels:['phone','whatsapp'],objectionHistory:[]},
    sentimentTrend:[65,68,70,71,71,71], dealVelocity:1.5, qualityScore:72,
    documents:[],
  },
];

export const PROPERTIES: Property[] = [
  { id:1, code:'2041', title:'Apto Beira Mar Premium', city:'Balneário Piçarras', type:'Apartamento',
    price:320000, area:68, bedrooms:2, beach:'80m', airbnb:true, status:'disponível',
    views:47, matches:3, yield:9.2, commission:9600, photo:'🏖', highlight:'Melhor custo-benefício da região', iptu:2800, condo:560, features:['piscina','churrasqueira','sacada','vaga'] },
  { id:2, code:'3098', title:'Casa Condomínio Fechado', city:'Penha', type:'Casa',
    price:480000, area:120, bedrooms:3, beach:'500m', airbnb:false, status:'disponível',
    views:31, matches:2, yield:6.5, commission:14400, photo:'🏡', highlight:'Segurança e privacidade total', iptu:3600, condo:800, features:['garagem','quintal','piscina'] },
  { id:3, code:'1055', title:'Studio Moderno Centro', city:'Barra Velha', type:'Studio',
    price:180000, area:38, bedrooms:1, beach:'300m', airbnb:true, status:'reservado',
    views:89, matches:5, yield:12.1, commission:5400, photo:'🏙', highlight:'Maior yield Airbnb da carteira', iptu:1400, condo:380, features:['mobiliado','sacada','academia'] },
  { id:4, code:'4055', title:'Cobertura Vista Mar', city:'Navegantes', type:'Cobertura',
    price:650000, area:200, bedrooms:3, beach:'Frente mar', airbnb:true, status:'disponível',
    views:22, matches:1, yield:7.8, commission:19500, photo:'🌊', highlight:'Único disponível frente ao mar', iptu:6500, condo:1200, features:['piscina_priv','gourmet','2_vagas'] },
  { id:5, code:'2088', title:'Apto 1 Dorm Centro', city:'Balneário Piçarras', type:'Apartamento',
    price:195000, area:45, bedrooms:1, beach:'200m', airbnb:true, status:'disponível',
    views:63, matches:4, yield:11.0, commission:5850, photo:'🏠', highlight:'Alta liquidez Airbnb', iptu:1800, condo:420, features:['mobiliado','sacada'] },
  { id:6, code:'6077', title:'Terreno Vista Mar', city:'Penha', type:'Terreno',
    price:280000, area:360, bedrooms:0, beach:'150m', airbnb:false, status:'disponível',
    views:18, matches:2, yield:0, commission:8400, photo:'🌳', highlight:'Oportunidade de construção', iptu:2200, condo:0, features:['escriturado'] },
  { id:7, code:'3122', title:'Kitnet Mobiliada', city:'Balneário Piçarras', type:'Studio',
    price:165000, area:32, bedrooms:1, beach:'400m', airbnb:true, status:'disponível',
    views:42, matches:3, yield:13.2, commission:4950, photo:'🏘', highlight:'Maior rentabilidade por m²', iptu:1200, condo:280, features:['mobiliado','elevador'] },
];

export const MSGS_INIT: Message[] = [
  { id:1, from:'client', text:'Oi! Vi o anúncio de vocês. Tenho 50 mil de entrada e renda de 8 mil. Quero algo em Piçarras.', time:'09:12', sentiment:'positivo' },
  { id:2, from:'ai',     text:'Olá! 😊 Com R$ 50k de entrada e R$ 8k/mês de renda, você tem capacidade para imóveis até R$ 350.000. Tenho opções em Balneário Piçarras! Você prefere apartamento ou casa?', time:'09:12', sentiment:'neutro' },
  { id:3, from:'client', text:'Apartamento, de preferência perto da praia', time:'09:14', sentiment:'positivo' },
  { id:4, from:'ai',     text:'Perfeito! Separei 2 opções ideais:\n\n[2041] Apto Beira Mar Premium\n💰 R$ 320.000 | 68m² | 2 dorms | 80m da praia ✨\n\n[2088] Apto 1 Dorm Centro\n💰 R$ 195.000 | 45m² | 200m da praia\n\nQual chamou mais atenção?', time:'09:14', sentiment:'neutro' },
  { id:5, from:'client', text:'O 2041 parece ótimo! Tem como ver na quinta?', time:'09:16', sentiment:'muito_positivo' },
  { id:6, from:'ai',     text:'✅ Visita confirmada! Quinta-feira às 14h no Apto 2041. Vou enviar o endereço e um lembrete na véspera 👏', time:'09:16', sentiment:'neutro' },
];

export const STAGES: Stage[] = [
  { key:'novo',       label:'Novos',        color:'#5A7090', icon:'◌', order:0 },
  { key:'qualificado', label:'Qualificados', color:'#3B82F6', icon:'◈', order:1 },
  { key:'agendado',   label:'Agendados',    color:'#8B5CF6', icon:'◉', order:2 },
  { key:'visitou',    label:'Visitaram',    color:'#F59E0B', icon:'⊕', order:3 },
  { key:'proposta',   label:'Proposta',     color:'#06B6D4', icon:'⊛', order:4 },
  { key:'fechado',    label:'Fechado',      color:'#10B981', icon:'✓', order:5 },
  { key:'perdido',    label:'Perdido',      color:'#F43F5E', icon:'✗', order:6 },
];


// ── Constantes de mapeamento ─────────────────────────────────────────
export const SRC_IC: Record<string, string> = {
  instagram:'📸', google:'🔍', indicacao:'🤝', trafego_pago:'🎯',
  organico:'🌱', tiktok:'🎵', facebook:'👥', zap:'🏢', vivareal:'🏠',
};
export const SRC_LB: Record<string, string> = {
  instagram:'Instagram', google:'Google', indicacao:'Indicação',
  trafego_pago:'Tráfego Pago', organico:'Orgânico', tiktok:'TikTok',
  facebook:'Facebook', zap:'ZAP Imóveis', vivareal:'VivaReal',
};
export const TC: Record<string, string> = {
  hot:'#F43F5E', warm:'#F59E0B', cold:'#3B82F6',
};
export const SC: Record<string, string> = {
  novo:'#5A7090', qualificado:'#3B82F6', agendado:'#8B5CF6',
  visitou:'#F59E0B', proposta:'#06B6D4', fechado:'#10B981', perdido:'#F43F5E',
};
